id: mongo-test-ctl
kind: ReplicationController
apiVersion: v1
metadata:
  name: mongo
spec:
  replicas: 3
  selector:
    name: mongo
    environment: test
  template:
    spec:
      manifest:
        version: v1
        id: mongo-test
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
        - name: mongo-sidecar
          image: leportlabs/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "name=mongo,environment=test"
    metadata:
      labels:
        name: mongo
        environment: test
