runtime: custom
vm: true
api_version: 1

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 20
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.8

network:
  forwarded_ports:
  - 8080
  - 1935
  instance_tag: rtmp
  #name: <network-name>

resources:
  cpu: .5
  memory_gb: 1
  disk_size_gb: 10

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60