runtime: custom
module: rtmp
vm: true
api_version: 1
#instance_class: F1
threadsafe: yes

handlers:
- url: .*
  script: dynamic

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 20
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5

network:
  forwarded_ports:
  - 1935
  instance_tag: rtmp
  name: default

resources:
  cpu: 0.5
  memory_gb: 0.5
  disk_size_gb: 10

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60